import fs from 'node:fs';
import { deriveDataviz, DATAVIZ_LENGTHS } from './lib/dataviz.mjs';

const PRIM = 'packages/tokens/tokens/primitive/color.json';
const SEM = 'packages/tokens/tokens/semantic/color.json';
const prim = JSON.parse(fs.readFileSync(PRIM, 'utf8')).color;

const index = new Map();
for (const [scale, steps] of Object.entries(prim)) {
  for (const [step, def] of Object.entries(steps)) {
    if (step === '$description' || typeof def?.$value !== 'string') continue;
    const hex = def.$value.toLowerCase();
    if (!index.has(hex)) index.set(hex, []);
    index.get(hex).push({ scale, step });
  }
}
const lookup = (hex, scheme) =>
  (index.get(hex.toLowerCase()) ?? []).find((h) => (scheme === 'dark') === h.scale.endsWith('-dark'));

const DESC = {
  categorical:
    'Series identity — which series is this. Assigned in FIXED ORDER and never cycled: a ninth series folds into "Other", small multiples or facets rather than reusing slot 1. The ORDER is the colour-vision-safety mechanism, not cosmetics — it is SEARCHED by scripts/lib/dataviz.mjs, not chosen.',
  sequential:
    'Magnitude — how much. One hue, low (1) to high (7), wearing the brand: a single-hue ramp stays separable for every kind of colour vision because LIGHTNESS carries it, not hue. Interpolated rather than sampled, which is why this is the one data-viz scale with no primitive behind it — see the note on slot 1.',
  diverging:
    'Polarity — which side of a baseline. Cool (1) through a neutral midpoint (4) to warm (7). Deliberately NOT brand-derived: a green brand would give green-vs-red, the worst pairing for the commonest colour-vision deficiency.',
};

const SEQ_NOTE =
  ' NO PRIMITIVE, and that is correct rather than a gap: this ramp is derived from the BRAND, and a brand ramp is never a primitive — rampFrom lands the client hex exactly on step 9, so no Radix ramp matches it. It is also INTERPOLATED, because only ~4 steps of a Radix light ramp clear 2:1 against the surface and sampling 7 bins from those produced literal duplicates.';

const surfaces = { light: ['#fcfcfc', '#f9f9f9'], dark: ['#191919', '#111111'] };
const d = deriveDataviz({ seedHex: '#46a758', neutral: 'pure', surfaces });

const json = JSON.parse(fs.readFileSync(SEM, 'utf8'));
let refs = 0, hexes = 0;
for (const [scale, n] of Object.entries(DATAVIZ_LENGTHS)) {
  for (let i = 1; i <= n; i++) {
    const hex = d.light[scale][i - 1];
    const hit = lookup(hex, 'light');
    const key = `background-dataviz-${scale}-${i}`;
    if (hit) refs++; else hexes++;
    json.color[key] = {
      $value: hit ? `{color.${hit.scale}.${hit.step}}` : hex,
      $type: 'color',
      $description:
        `${DESC[scale]} Slot ${i} of ${n}.` +
        (hit ? '' : SEQ_NOTE) +
        ' GENERATED by scripts/lib/dataviz.mjs from the brand seed — edit the derivation, never this value.',
    };
  }
}
fs.writeFileSync(SEM, JSON.stringify(json, null, 2) + '\n');

const dark = [];
for (const [scale, n] of Object.entries(DATAVIZ_LENGTHS)) {
  for (let i = 1; i <= n; i++) {
    const hex = d.dark[scale][i - 1];
    const hit = lookup(hex, 'dark');
    dark.push(`  --color-background-dataviz-${scale}-${i}: ${hit ? `var(--color-${hit.scale}-${hit.step})` : hex};`);
  }
}
fs.writeFileSync('/tmp/dataviz-dark.css', dark.join('\n') + '\n');
console.log(`light: ${refs} primitive refs, ${hexes} hex (interpolated sequential)`);
console.log('dark block → /tmp/dataviz-dark.css');
