/**
 * Generate a baseline Storybook story per component, from the SAME extractor the
 * doc pages use (apps/site/src/data/component-api.ts) and the SAME grouping the
 * site nav uses (apps/site/src/data/catalog.ts).
 *
 * WHY GENERATED, NOT AUTHORED: hand-writing 60+ story files creates a second
 * source of truth for prop names, types and defaults — exactly the drift the
 * generated API tables exist to prevent. A rename in a component silently
 * orphans a hand-written argType; here it just regenerates.
 *
 * WHY THE OUTPUT IS GITIGNORED: these files are build artifacts. They are
 * regenerated by `npm run storybook`, so a stale one cannot be committed and go
 * unnoticed. Do not edit anything under src/generated/ — edit the component.
 *
 * AUTHORED STORIES WIN. A hand-written `src/<slug>.stories.ts` suppresses
 * generation for that component entirely. That is the escape hatch: a generated
 * story can show a component's API, but it cannot invent good sample data (see
 * the complex-prop note below), so the interesting specimens stay hand-written.
 *
 * Run: node --experimental-strip-types scripts/generate-stories.ts
 */
import { mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { componentApi, type ApiProp } from '../apps/site/src/data/component-api.ts';
import { catalog } from '../apps/site/src/data/catalog.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LIT_DIR = path.join(ROOT, 'apps', 'storybook', 'src');
const ASTRO_DIR = path.join(ROOT, 'apps', 'storybook-astro', 'src');

/** kebab attribute → camel property, so args can be assigned straight onto the element. */
const camel = (s: string) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

/**
 * Defaults are emitted as RAW SOURCE, copied from the component. That is only safe
 * for self-contained literals — a default like `LABEL_TYPE.md` references a binding
 * that does not exist in the story file and would be a ReferenceError at import
 * time, taking the whole Storybook down rather than just one story.
 */
function safeDefault(raw: string | undefined): string | undefined {
  if (raw === undefined) return undefined;
  const v = raw.trim();
  if (/^'[^'\\]*'$/.test(v) || /^"[^"\\]*"$/.test(v)) return v;
  if (/^-?\d+(\.\d+)?$/.test(v)) return v;
  if (v === 'true' || v === 'false' || v === 'null') return v;
  if (v === '[]' || v === '{}') return v;
  return undefined;
}

/**
 * Does this prop hold a list the component will iterate?
 *
 * This matters more than it looks. A component like esa-breadcrumbs does
 * `items.map(...)` with no guard, so rendering it with the prop left undefined
 * throws — and because the Astro half PRE-RENDERS every story during
 * `storybook build`, one such crash fails the entire build, not just that story.
 * Supplying `[]` keeps it renderable (empty, but honest).
 */
function isListType(type: string): boolean {
  return /\[\]\s*$/.test(type.replace(/\s*\|\s*(undefined|null)\s*/g, '').trim());
}

/** Literal-union type → the option list, e.g. `'xs' | 'sm'` → ["xs", "sm"]. */
function unionOptions(type: string): string[] | null {
  const parts = type.split('|').map((s) => s.trim());
  if (parts.length < 2) return null;
  const lits = parts.filter((p) => /^'[^']*'$/.test(p)).map((p) => p.slice(1, -1));
  // Every non-literal member must be undefined/null, or this isn't a plain enum.
  const rest = parts.filter((p) => !/^'[^']*'$/.test(p));
  if (lits.length < 2 || rest.some((r) => r !== 'undefined' && r !== 'null')) return null;
  return lits;
}

function controlFor(p: ApiProp): string {
  const opts = unionOptions(p.type);
  if (opts) {
    const kind = opts.length <= 4 ? 'inline-radio' : 'select';
    return `{ control: '${kind}', options: ${JSON.stringify(opts)} }`;
  }
  const t = p.type.replace(/\s*\|\s*(undefined|null)/g, '').trim();
  if (t === 'boolean') return `{ control: 'boolean' }`;
  if (t === 'number') return `{ control: 'number' }`;
  if (t === 'string') return `{ control: 'text' }`;
  // Arrays of option objects, element refs, unions of string|string[] — a control
  // here would produce garbage, and no generator can invent meaningful sample data.
  // Disabled on purpose: the row still documents the prop and its type.
  return `{ control: false }`;
}

/** Components whose generated story renders empty because their data props can't be synthesised. */
const thin: string[] = [];

/**
 * Boolean props that gate whether an OVERLAY renders anything at all.
 *
 * Deliberately just these two. An earlier version also matched `active` and
 * `show`, which silently broke esa-button — `active` there is a visual state, not
 * a visibility gate, so every generated button rendered stuck in its active
 * style. A false match here changes how a component LOOKS with no error anywhere,
 * so keep this list narrow and literal rather than clever.
 */
const GATE = /^(open|visible)$/;

/**
 * Slot names a `.astro` component exposes, default slot first.
 *
 * Content-taking components get their content from CHILDREN, not props, so a
 * props-only story renders an empty shell — esa-button came out as a correctly
 * styled button with no label. 18 of the 31 .astro components are in this
 * category. Slot content is passed as `args.slots.<name>`; `default` maps to the
 * unnamed `<slot />`.
 */
function slotNames(slug: string): string[] {
  const file = path.join(ROOT, 'packages', 'ecology', 'src', 'components', `${slug}.astro`);
  if (!existsSync(file)) return [];
  const src = readFileSync(file, 'utf8');
  const names = new Set<string>();
  for (const m of src.matchAll(/<slot(\s[^>]*)?\/?>/g)) {
    const named = m[1]?.match(/name=["']([^"']+)["']/);
    names.add(named ? named[1] : 'default');
  }
  return [...names].sort((a, b) => (a === 'default' ? -1 : b === 'default' ? 1 : a.localeCompare(b)));
}

function storySource(slug: string, name: string, group: string, kind: 'wc' | '.astro'): string {
  const api = componentApi[slug];
  const props = api.props.filter((p) => !p.propertyOnly);

  const argTypeLines: string[] = [];
  const argLines: string[] = [];
  let synthesised = false;

  for (const p of props) {
    const key = camel(p.propertyName ?? p.name);
    const bits = [controlFor(p).slice(1, -1).trim()];
    // Show the attribute spelling in the docs when it differs from the property.
    if (p.name !== key) bits.push(`name: '${p.name}'`);
    if (p.description) bits.push(`description: ${JSON.stringify(p.description)}`);
    argTypeLines.push(`    ${key}: { ${bits.join(', ')} },`);

    const def = safeDefault(p.default);
    if (GATE.test(p.name) && p.type.replace(/\s*\|\s*(undefined|null)/g, '').trim() === 'boolean') {
      // Overlays (dialogs, palettes, back-to-top) ship closed, which is right for an
      // app and useless in a workbench — the story would render a 0px-tall nothing.
      // Open them, deliberately overriding the component's own default.
      argLines.push(`    ${key}: true, // opened for the workbench; the component's own default is ${p.default ?? 'false'}`);
    } else if (def !== undefined) {
      argLines.push(`    ${key}: ${def},`);
    } else if (isListType(p.type)) {
      // No usable default and the component will iterate it — see isListType.
      argLines.push(`    ${key}: [], // synthesised: component iterates this; real data needs an authored story`);
      synthesised = true;
    }
  }

  // Slot content — .astro only. `default` is the unnamed <slot />; named slots
  // keep their name. Placeholder text, so the component at least renders with
  // something in it; a real specimen is what an authored story is for.
  const slots = kind === '.astro' ? slotNames(slug) : [];
  if (slots.length) {
    const label = name.replace(/([a-z])([A-Z])/g, '$1 $2');
    const entries = slots.map((s) =>
      s === 'default' ? `default: '${label}'` : `${JSON.stringify(s)}: '${s}'`,
    );
    argLines.push(`    slots: { ${entries.join(', ')} },`);
  }

  if (synthesised) thin.push(slug);

  const src = `packages/ecology/src/components/${slug}.${kind === 'wc' ? 'ts' : 'astro'}`;
  const header = `// GENERATED FILE — DO NOT EDIT.
// Source of truth: ${src}
// Regenerate: npm run storybook (or node --experimental-strip-types scripts/generate-stories.ts)
// To replace this with a real specimen, write apps/storybook${kind === 'wc' ? '' : '-astro'}/src/${slug}.stories.ts
// by hand — an authored story suppresses generation for this component.
`;

  if (kind === 'wc') {
    return `${header}import '@esa/ecology/${slug}';

export default {
  title: '${group}/${slug}',
  component: '${slug}',
  tags: ['autodocs'],
  argTypes: {
${argTypeLines.join('\n')}
  },
  args: {
${argLines.join('\n')}
  },
  // Args are assigned as PROPERTIES, not attributes — Lit reflects the ones it
  // declares reflective, and this avoids stringifying objects and arrays.
  render: (args: Record<string, unknown>) => {
    const el = document.createElement('${slug}');
    for (const [k, v] of Object.entries(args)) {
      if (v !== undefined) (el as Record<string, unknown>)[k] = v;
    }
    return el;
  },
};

export const Default = {};
`;
  }

  return `${header}import Component from '@esa/ecology/${slug}.astro';

export default {
  title: '${group}/${slug}',
  component: Component,
  tags: ['autodocs'],
  argTypes: {
${argTypeLines.join('\n')}
  },
  args: {
${argLines.join('\n')}
  },
};

export const Default = {};
`;
}

// ── Generate ────────────────────────────────────────────────────────────────

let generated = 0;
const skipped: string[] = [];
const noApi: string[] = [];

for (const dir of [LIT_DIR, ASTRO_DIR]) {
  rmSync(path.join(dir, 'generated'), { recursive: true, force: true });
  mkdirSync(path.join(dir, 'generated'), { recursive: true });
}

for (const group of catalog) {
  for (const entry of group.entries) {
    // Reference components (AG Grid & friends) wrap external libraries and have no
    // source file here — nothing to extract, nothing to render.
    if (entry.kind === 'reference') continue;

    const api = componentApi[entry.slug];
    if (!api) {
      noApi.push(entry.slug);
      continue;
    }

    const outDir = entry.kind === 'wc' ? LIT_DIR : ASTRO_DIR;

    // An authored story wins — never clobber or duplicate hand-written work.
    if (existsSync(path.join(outDir, `${entry.slug}.stories.ts`))) {
      skipped.push(entry.slug);
      continue;
    }

    writeFileSync(
      path.join(outDir, 'generated', `${entry.slug}.stories.ts`),
      storySource(entry.slug, entry.name, group.label, entry.kind),
      'utf8',
    );
    generated++;
  }
}

console.log(`[stories] generated ${generated}`);
if (skipped.length) console.log(`[stories] skipped ${skipped.length} with authored stories: ${skipped.join(', ')}`);
if (noApi.length) console.log(`[stories] WARNING — no extracted API, no story: ${noApi.join(', ')}`);
// Not a warning — a work list. These render as empty shells because their content
// comes from array props no generator can invent. They are the components where a
// hand-written story earns its keep; say so rather than let the sidebar imply coverage.
if (thin.length) {
  console.log(`[stories] ${thin.length} render empty pending an authored story: ${thin.join(', ')}`);
}
